# Generated by Django 5.1.1 on 2024-10-09 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TextClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('flavor_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_clues.flavortext')),
            ],
        ),
    ]
