# Generated by Django 5.1.1 on 2024-10-16 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_clues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationFlavorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FlavorText',
            new_name='DescriptorFlavorText',
        ),
        migrations.RemoveField(
            model_name='textclue',
            name='flavor_text',
        ),
        migrations.AddField(
            model_name='textclue',
            name='descriptor1_flavor_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptor1', to='text_clues.descriptorflavortext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textclue',
            name='descriptor2_flavor_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptor2', to='text_clues.descriptorflavortext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textclue',
            name='descriptor3_flavor_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptor3', to='text_clues.descriptorflavortext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textclue',
            name='occupation_flavor_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='text_clues.occupationflavortext'),
            preserve_default=False,
        ),
    ]
