# Generated by Django 5.1.1 on 2024-10-18 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_clues', '0002_occupationflavortext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTextClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='textclue',
            name='story_clue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='text_clues.storytextclue'),
            preserve_default=False,
        ),
    ]
