version: '3'
services:
  web:
    extends:
      file: base-compose.yaml
      service: web
    build:
      context: ./murder_mystery
      dockerfile: Dockerfile
    env_file:
      - ./.env.staging
  db:
    extends:
      file: base-compose.yaml
      service: db
    volumes:
      - staging-data:/var/lib/postgresql/data
    env_file:
      - ./.env.staging.db
  nginx-proxy:
    extends:
      file: base-compose.yaml
      service: nginx-proxy
  acme-companion:
    extends:
      file: base-compose.yaml
      service: acme-companion
    env_file:
      - ./.env.staging.proxy-companion

volumes:
  staging-data:
  static_volume:
  certs:
  html:
  vhost:
  acme:
