version: '3'
services:
  db:
    image: mysql:9.0
    container_name: murder_mystery_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: murder_mystery_backend
    command: sh -c "/app/starter_script.sh"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy

  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: murder_mystery_backend_test
    command: sh -c "/app/starter_test_script.sh"
    volumes:
      - .:/app
volumes:
  data:
