version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: murder-mystery-backend
    command: gunicorn murder_mystery.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    container_name: murder-mystery-postgres-db
    restart: always
    volumes:
      - prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env.prod.db

volumes:
  prod-data:
