# Generated by Django 5.1.1 on 2024-10-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuspoint',
            name='answer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
