name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./murder_mystery/docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "test-backend"
          test-command: "python manage.py test"
