# Generated by Django 5.1.1 on 2024-10-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_clues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='where',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
