# Generated by Django 5.1.1 on 2024-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('location_hint1', models.TextField()),
                ('location_hint2', models.TextField()),
                ('location_hint3', models.TextField()),
            ],
        ),
    ]
