# Generated by Django 5.1.1 on 2024-10-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_clues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclue',
            name='location',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
