# Generated by Django 5.1.1 on 2024-10-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('real_name', models.CharField(max_length=32)),
                ('character_name', models.CharField(max_length=32)),
                ('past_or_future', models.CharField(choices=[('p', 'Past'), ('f', 'Future')], default='f', max_length=16)),
                ('occupation', models.CharField(max_length=32)),
                ('descriptor1', models.CharField(max_length=32)),
                ('descriptor2', models.CharField(max_length=32)),
                ('descriptor3', models.CharField(max_length=32)),
                ('solo', models.BooleanField()),
                ('prefered_partner', models.CharField(max_length=32)),
            ],
        ),
    ]
