# Generated by Django 5.1.1 on 2024-10-26 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=32)),
                ('character_name', models.CharField(max_length=32)),
                ('past_or_future', models.CharField(choices=[('p', 'Past'), ('f', 'Future')], default='f', max_length=16)),
                ('occupation', models.CharField(max_length=32)),
                ('descriptor1', models.CharField(max_length=32)),
                ('descriptor2', models.CharField(max_length=32)),
                ('descriptor3', models.CharField(max_length=32)),
                ('solo', models.BooleanField()),
                ('preferred_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='I_choose_you_to_be_my_partner', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
