# Generated by Django 5.1.1 on 2024-10-09 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='future_character', to='characters.character')),
                ('past_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='past_character', to='characters.character')),
            ],
        ),
    ]
