# Generated by Django 5.1.1 on 2024-10-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_clues', '0001_initial'),
        ('characters', '0001_initial'),
        ('location_clues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_character', to='characters.character')),
                ('past_character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_character', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='TeamToClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('found', models.BooleanField(default=False)),
                ('location_hints', models.SmallIntegerField(default=0)),
                ('tries', models.SmallIntegerField(default=0)),
                ('character_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character_clues.characterclue')),
                ('location_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_clues.locationclue')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
