# Generated by Django 5.1.1 on 2024-10-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_prefered_partner'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='future_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_character', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='team',
            name='past_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_character', to='characters.character'),
        ),
    ]
