# Generated by Django 5.1.1 on 2024-10-16 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_future_character_and_more'),
        ('text_clues', '0002_occupationflavortext_and_more'),
        ('video_clues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamToClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('found', models.BooleanField(default=False)),
                ('location_hints', models.SmallIntegerField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('text_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text_clues.textclue')),
                ('video_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_clues.videoclue')),
            ],
        ),
    ]
