name: Django CI

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  # Integration Test
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build container"
        run: COMPOSE_PROJECT_NAME=past-vs-present-murder-mystery docker compose -f test-compose.yaml build
      - name: "Run Tests"
        run: docker run --rm past-vs-present-murder-mystery-test-backend sh -c "python manage.py test"
