name: Django CI

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  # Integration Test
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: cd murder_mystery && docker compose -f compose.yml up test-backend -d --wait
      - name: "Run Tests"
        run: docker exec -it murder_mystery_backend_test python manage.py test
