name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      # Check out the repository
      - uses: actions/checkout@v4
    
      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./murder_mystery/compose.yml"
          up-flags: "--build"
          test-container: "test-backend"
          test-command: "python manage.py test"
